### ISSUE TITLE
Create packages

### ISSUE THREAD

**Issue by KOLANICH** [chrischute/pbt#1]

**Comment by chrischute** [comment]
Dependencies are listed in the `environment.yml` file, and you can create a virtual environment with `conda env create -f environment.yml`. Does this solve your issue?

**Comment by KOLANICH** [comment]
No, I really meant packages: right directory structure (all the files should be moved into the dir with the name of your package, or you can split server, client and the rest of code into separate packages, using namespace packages), `setup.py` and `setup.cfg` (all the metadata is stored in `setup.cfg`, `setup.py` in the simplest case contains only 2 lines: `from setuptools import setup` and `setup()`) capable to produce wheels and be installed by `pip` automatically with all the needed dependencies.

This is needed if one wants to use foreign code as a library.

**Comment by chrischute** [comment]
Thanks for the suggestion -- I'm not planning to refactor into packages for now, but would welcome a PR doing so.
