### ISSUE TITLE
Allow working without client and server, by splitting networking part and creating interfaces allowing plugging server into client directly

### ISSUE THREAD

**Issue by KOLANICH** [chrischute/pbt#2]

**Comment by chrischute** [comment]
Could you clarify the design a little bit? I'm open to a redesign of the networking components, e.g. switching to [pyro](https://pyro4.readthedocs.io/en/stable/index.html).

**Comment by KOLANICH** [comment]
>Could you clarify the design a little bit?

It's just a sketch. The goal is to run the thing on a single machine in a single process without any servers and clients. Because to use this as a library running a server means an additional parameter: port and some code maintaining a server. I have looked into the architecture a bit. You have 2 classes actuarry storing bodies of methods. It may make  sense  not to create `SyncManager` objects for some cases, but use methods directly, maybe by replacing `self._client` not by a `SyncManager` object, but by the actual `PBTServer` object (`PBTServer` needs to be modified not to start server automatically).

**Comment by chrischute** [comment]
I don't plan on doing this redesign myself, but I'm open to a PR if someone else wants to take this on. Closing for now.
